### ISSUE TITLE
likeminded.pl vs private accounts: Load books from CSV-file

### ISSUE THREAD

**Issue by andre-st** [andre-st/goodreads#12]
> I see that to use likeminded, I need to make my shelf public, could you also provide the option of using exported shelf (.csv) directly for book ID instead of user ID.
(contact via Goodreads message)

**Comment by andre-st** [comment]
likeminded.pl supports the --cookie parameter, now. So one could use this as a work-around in order to access private shelves

**Comment by Tikotik** [comment]
Nice. But what cookie parameter misses instead of importing is : you can create/edit a csv without bothering about changing GR shelves, also sometimes you want to include a small bunch of books to compare directly (but u don't want that to advertise to ur friends).

It would be nice to have a example template of json/other format of goodreads book id's to directly run on them.

**Comment by andre-st** [comment]
It would be a list with author IDs: https://github.com/andre-st/goodreads/blob/master/likeminded.md#first-version-compared-books-not-authors

Is a simple text file sufficient for you?
```console
$ cat authors.lst
1234567
12345689
654321
```

**Comment by andre-st** [comment]
This became obsolete with #25 
You can pass your GR login credentials to likeminded.pl and other programs now. 
If there are problems, it should be a new issue.
